name: VoitAC
version: '1.0'
main: org.voitac.anticheat.AnticheatPlugin
api-version: '1.16'
authors: [Tawny]
description: Multi-version anti-cheat with modernized movement and combat checks
load: POSTWORLD
depend:
  - ProtocolLib
